greeting: "hello from config-server(github)"
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml
    redis:
      host: 127.0.0.1
      port: 6379
management:
  endpoints:
    web:
      exposure:
        include: "*"