greeting: "hello from config-server(github)"
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  liquibase:
    enabled: false